#**Introduzione alle funzionalità di NumPy**

**Obiettivi:**
* Conoscere le funzionalità principali di NumPy
* Saper creare, manipolare e operare su array multidimensionali
* Approfondire concetti come slicing, broadcasting, aggregazioni, reshaping e algebra lineare
* Applicare quanto appreso attraverso esercizi pratici
* Utilizzare NumPy per generare dati casuali e simulare situazioni reali

##1. Introduzione a NumPy e creazione degli array

### 1.1 Introduzione

* NumPy è una libreria fondamentale per il calcolo scientifico in Python.
* Fornisce un potente oggetto array multidimensionale, funzioni per operazioni matematiche, statistiche e molto altro.
* In questo notebook esploreremo le funzionalità principali di NumPy con esempi ed esercizi.



### 1.2 Importazione della libreria

In [1]:
import numpy as np

# Verifica la versione di NumPy
print("NumPy version:", np.__version__)

NumPy version: 2.1.3


### 1.3 Creazione di array

* Array creato da una lista

In [2]:
lista = [1, 2, 3, 4, 5]
arr = np.array(lista)
print("Array creato da una lista:", arr)

Array creato da una lista: [1 2 3 4 5]


* Array con valori in sequenza

In [4]:
# np.arange: genera array con valori in sequenza (simile a range())
# punto iniziale (incluso), finale (escluso), step
arr_range = np.arange(0, 10, 2)  # da 0 a 10 (non incluso) con step 2
print("Array con np.arange:", arr_range)

# np.linspace: genera array con un numero specifico di valori equidistanti
# punto iniziale (incluso), punto finale (escluso), numero di punti (invece di step)
arr_lin = np.linspace(0, 1, 5)   # 5 valori da 0 a 1
print("Array con np.linspace:", arr_lin)

Array con np.arange: [0 2 4 6 8]
Array con np.linspace: [0.   0.25 0.5  0.75 1.  ]


* Alcuni esempi di matrici

In [5]:
zeros = np.zeros((3, 4))    # matrice 3x4 di zeri
ones = np.ones((2, 5))      # matrice 2x5 di uni
full = np.full((2, 3), 7)   # matrice 2x3 con valore 7

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Full:\n", full)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Full:
 [[7 7 7]
 [7 7 7]]


### 1.4 Conversione degli elementi di un array

Per convertire gli elementi di un array da `float` a `int` utilizzando Numpy, possiamo seguire il seguente esempio:

In [6]:
import numpy as np

# Creiamo un array di float
arr_float = np.array([1.5, 2.7, 3.9, 4.1])

# Convertiamolo in un array di interi
arr_int = arr_float.astype(int)

print("Array di float:", arr_float)
print("Array di interi:", arr_int)

Array di float: [1.5 2.7 3.9 4.1]
Array di interi: [1 2 3 4]


### 1.5 Esercizi di consolidamento

#### **Esercizio 1**
Crea un array da una lista contenente i numeri da 10 a 19. Moltiplica ogni elemento dell'array per 3 e stampa il risultato.
<br><br>

#### **Esercizio 2**
Utilizza `np.arange` per creare un array di numeri pari tra 1 e 24 (estremi eventualmente inclusi). Trasforma questo array in una matrice di dimensione $3\times ?$, scegliendo una dimensione che sia compatibile con il numero di elementi.
<br><br>

#### **Esercizio 3**
Usa `np.linspace` per generare 8 valori compresi tra -1 e 1. Visualizza il tipo di dato dell'array creato.


In [17]:
# Es 1.
# Crea un array da una lista contenente i numeri da 10 a 19. Moltiplica ogni elemento dell'array per 3 e stampa il risultato.

list1 = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
arrayList = np.array(list1)
arrayList2 = arrayList * 3

print(arrayList)
print(arrayList2)

[10 11 12 13 14 15 16 17 18 19]
[30 33 36 39 42 45 48 51 54 57]


In [9]:
# Es 1. Bis

list3 = np.arange(10, 20, 1)
list4 = list3 * 3

print(list3)
print(list4)



[10 11 12 13 14 15 16 17 18 19]
[30 33 36 39 42 45 48 51 54 57]


In [10]:
# Es 2.
# Utilizza `np.arange` per creare un array di numeri pari tra 1 e 24 (estremi eventualmente inclusi). 
# Trasforma questo array in una matrice di dimensione 3 x ?
# scegliendo una dimensione che sia compatibile con il numero di elementi.

list5 = np.arange(1, 25, 1)
#matrix1 = np.ones(5,5)
matrixList5 = list5.reshape(3,-1)
matrixList6 = list5.reshape(4,-1)
print(list5)
#print(matrix1)
print(matrixList5)
print(matrixList6)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [11]:
# Esercizio 3
# Usa np.linspace per generare 8 valori compresi tra -1 e 1.
# Visualizza il tipo di dato dell'array creato.
list7 = np.linspace(-1,1,8)
print(list7)
print("Tipo di dato: ", list7.dtype)
print("Fine esercizio 3")

    

[-1.         -0.71428571 -0.42857143 -0.14285714  0.14285714  0.42857143
  0.71428571  1.        ]
Tipo di dato:  float64
Fine esercizio 3


In [ ]:
# Soluzione
import numpy as np

# list = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
# Rinomina la variabile list: Se hai sovrascritto list, 
# devi ripristinare la funzione built-in. Puoi farlo 
# eliminando o rinominando la variabile:
# del list  # Ripristina la funzione built-in `list`

# Esercizio 1
# Crea un array da una lista contenente i numeri da 10 a 19.
# Moltiplica ogni elemento dell'array per 3 e stampa il risultato.
print("Esercizio 1:")
lista_es1 = list(range(10, 20))
array_es1 = np.array(lista_es1)
array_es1_moltiplicato = array_es1 * 3
print(array_es1_moltiplicato)
print("Fine Esercizio 1\n")


# Esercizio 2
# Utilizza np.arange per creare un array di numeri pari tra 1 e 20.
# Trasforma questo array in una matrice di dimensione 3x?, scegliendo una dimensione compatibile.
print("Esercizio 2:")
array_pari = np.arange(2, 25, 2) # considero come elemento il primo numero pari nell'intervallo considerato
print(array_pari)
matrice_pari = array_pari.reshape(3, -1)  # -1 calcola automaticamente la seconda dimensione
print(matrice_pari)
print("Fine Esercizio 2\n")


# Esercizio 3
# Usa np.linspace per generare 8 valori compresi tra -1 e 1.
# Visualizza il tipo di dato dell'array creato.
print("Esercizio 3:")
valori_linspace = np.linspace(-1, 1, 8)
print(valori_linspace)
print("Tipo di dato:", valori_linspace.dtype)
print("Fine Esercizio 3")


Esercizio 1:
[30 33 36 39 42 45 48 51 54 57]
Fine Esercizio 1

Esercizio 2:
[ 2  4  6  8 10 12 14 16 18 20 22 24]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Fine Esercizio 2

Esercizio 3:
[-1.         -0.71428571 -0.42857143 -0.14285714  0.14285714  0.42857143
  0.71428571  1.        ]
Tipo di dato: float64
Fine Esercizio 3


##2. Indexing, slicing e operazioni element-wise

### 2.1 Indexing e slicing
* Indexing su un array 1D

In [20]:
arr = np.array([10, 20, 30, 40, 50])
print("Primo elemento:", arr[0])
print("Ultimo elemento:", arr[-1])

Primo elemento: 10
Ultimo elemento: 50


* Slicing su un array 1D

In [21]:
print("Elementi dal 2° al 4°:", arr[1:4])  # dall'indice 1 all'indice 3, 1 incluso, 4 escluso

Elementi dal 2° al 4°: [20 30 40]


* Indexing su array multidimensionali

In [26]:
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Elemento in posizione (1,2):", mat[1, 2])  # 6
print("Elemento in posizione (1,2):", mat[1][2])  # 6
print("Prima riga:", mat[0])
print("Prima riga:", mat[0][:])
print("Prima riga:", mat[[0], :])# maintiene la struttura matrice [[]]
print("Seconda colonna:", mat[:, 1])
print("Seconda colonna:\n", mat[:, [1]])# maintiene la struttura matrice [[]]

Elemento in posizione (1,2): 6
Elemento in posizione (1,2): 6
Prima riga: [1 2 3]
Prima riga: [1 2 3]
Prima riga: [[1 2 3]]
Seconda colonna: [2 5 8]
Seconda colonna:
 [[2]
 [5]
 [8]]


### 2.2 Operazioni element-wise

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

somma = a + b        # [5, 7, 9]
prodotto = a * b     # [4, 10, 18]
sottrazione = b - a  # [3, 3, 3]

print("Somma:", somma)
print("Prodotto:", prodotto)
print("Sottrazione:", sottrazione)

Somma: [5 7 9]
Prodotto: [ 4 10 18]
Sottrazione: [3 3 3]


### 2.3 Esercizi di consolidamento

#### **Esercizio 4**
Crea una matrice $3\times 3$ con valori da 1 a 9.
Estrai la seconda riga e assegnala a una variabile.
Cambia il valore dell'elemento centrale—ossia in posizione (1,1)—a 0 e visualizza la matrice aggiornata.
<br><br>

#### **Esercizio 5**
Dato l'array:

```arr = np.array([10, 20, 30, 40, 50, 60]) ```

usa lo slicing per creare un nuovo array che contenga solo gli elementi dal secondo al penultimo.
<br><br>

#### **Esercizio 6**
Crea due array di dimensione 4 contenenti numeri casuali (es. np.random.randint(0, 10, size=4)). Calcola il prodotto elemento per elemento e poi la somma degli elementi del risultato.

In [30]:
# Esercizio 4
# Crea una matrice 3x3 con valori da 1 a 9.
# Estrai la seconda riga e assegnala a una variabile.
# Cambia il valore dell'elemento centrale (1,1) a 0 e visualizza la matrice aggiornata.
matrice3x3 = np.arange(1,10).reshape(3,3)
print("Matrice originale: \n", matrice3x3)
# variableSecondaRiga = matrice3x3[:][1]
variableSecondaRiga = matrice3x3[1]
print("Seconda riga: ", variableSecondaRiga)
matrice3x3[1, 1] = 0
print("Seconda riga: ", variableSecondaRiga)
matrice3x3[1][1] = 0
print("Matrice originale: \n", matrice3x3)

Matrice originale: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Seconda riga:  [4 5 6]
Seconda riga:  [4 0 6]
Matrice originale: 
 [[1 2 3]
 [4 0 6]
 [7 8 9]]


In [31]:
# Esercizio 5
# Dato l'array arr = np.array([10, 20, 30, 40, 50, 60]), usa lo slicing per creare un nuovo array
# che contenga solo gli elementi dal secondo al penultimo.
arr = np.array([10, 20, 30, 40, 50, 60])
print("array originale: ", arr)
arr2 = arr[1:-1]
print("array modificato: ", arr2)

array originale:  [10 20 30 40 50 60]
array modificato:  [20 30 40 50]


In [33]:
# Esercizio 6
# Crea due array di dimensione 4 contenenti numeri casuali (es. np.random.randint(0, 10, size=4)).
# Calcola il prodotto elemento per elemento e poi la somma degli elementi del risultato.
arrDim4_1 = np.random.randint(0, 10, size=4)
print("Array 1: ", arrDim4_1)
arrDim4_2 = np.random.randint(0, 10, size=4)
print("Array 2: ", arrDim4_2)
prodottoArrDim4 = arrDim4_1 * arrDim4_2
print("Prodotto : ", prodottoArrDim4)
sommaArrDim4 = arrDim4_1 + arrDim4_2
print("Somma: ", sommaArrDim4)
sommaElementiProdotto = np.sum(sommaArrDim4)
print("Somma elementi prodotto: ", sommaElementiProdotto)

Array 1:  [5 2 8 0]
Array 2:  [8 1 2 6]
Prodotto :  [40  2 16  0]
Somma:  [13  3 10  6]
Somma elementi prodotto:  32


In [34]:
# Soluzione
import numpy as np

# Esercizio 4
# Crea una matrice 3x3 con valori da 1 a 9.
# Estrai la seconda riga e assegnala a una variabile.
# Cambia il valore dell'elemento centrale (1,1) a 0 e visualizza la matrice aggiornata.
print("Esercizio 4:")
matrice_3x3 = np.arange(1, 10).reshape(3, 3)
print("Matrice originale:\n", matrice_3x3)

seconda_riga = matrice_3x3[1, :]  # Estraggo la seconda riga
print("Seconda riga:\n", seconda_riga)

matrice_3x3[1, 1] = 0  # Modifico l'elemento centrale
print("Matrice aggiornata:\n", matrice_3x3)
print("Fine Esercizio 4\n")


# Esercizio 5
# Dato l'array arr = np.array([10, 20, 30, 40, 50, 60]), usa lo slicing per creare un nuovo array
# che contenga solo gli elementi dal secondo al penultimo.
print("Esercizio 5:")
arr = np.array([10, 20, 30, 40, 50, 60])
sotto_array = arr[1:-1]  # Dal secondo elemento (indice 1) al penultimo (indice -2)
print("Sotto-array:\n", sotto_array)
print("Fine Esercizio 5\n")


# Esercizio 6
# Crea due array di dimensione 4 contenenti numeri casuali (es. np.random.randint(0, 10, size=4)).
# Calcola il prodotto elemento per elemento e poi la somma degli elementi del risultato.
print("Esercizio 6:")
array1 = np.random.randint(0, 10, size=4)
array2 = np.random.randint(0, 10, size=4)

print("Array 1:\n", array1)
print("Array 2:\n", array2)

prodotto_elementi = array1 * array2 # prodotto elemento per elemento
print("Prodotto elemento per elemento:\n", prodotto_elementi)
somma_prodotto = np.sum(prodotto_elementi) # somma degli elementi del prodotto
print("Somma degli elementi del prodotto:\n", somma_prodotto)
print("Fine Esercizio 6")


Esercizio 4:
Matrice originale:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Seconda riga:
 [4 5 6]
Matrice aggiornata:
 [[1 2 3]
 [4 0 6]
 [7 8 9]]
Fine Esercizio 4

Esercizio 5:
Sotto-array:
 [20 30 40 50]
Fine Esercizio 5

Esercizio 6:
Array 1:
 [7 2 1 2]
Array 2:
 [1 3 0 6]
Prodotto elemento per elemento:
 [ 7  6  0 12]
Somma degli elementi del prodotto:
 25
Fine Esercizio 6


## 3. Broadcasting e funzioni universali

### 3.1 Broadcasting

In [35]:
a = np.array([1, 2, 3])
b = 10  # uno scalare
print("Somma con scalare:", a + b)  # ogni elemento di a viene sommato a 10

# Esempio con array 2D e 1D:
mat = np.array([[1, 2, 3],
                [4, 5, 6]])
vett = np.array([10, 20, 30])
print("Somma di matrice e vettore:", mat + vett)

Somma con scalare: [11 12 13]
Somma di matrice e vettore: [[11 22 33]
 [14 25 36]]


### 3.2 Funzioni universali (ufuncs)

In [38]:
arr = np.array([0, np.pi/2, np.pi])
print("array: ", arr)

# Funzioni trigonometriche
sin_val = np.sin(arr)
cos_val = np.cos(arr)

# Funzioni esponenziali e logaritmiche
exp_val = np.exp(arr)# x = 3.14159265  exp_x = math.exp(x)
log_val = np.log(np.array([1, 10, 100])) # natual log : e^y = 1 or 10 or 100
# ln_10 = math.log(10)
# log_exp(10) =  2.30258509
# log10_10 = math.log10(10) = 1

print("Seno:", sin_val)
print("Coseno:", cos_val)
print("Esponenziale:", exp_val)
print("Logaritmo:", log_val)

array:  [0.         1.57079633 3.14159265]
Seno: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Coseno: [ 1.000000e+00  6.123234e-17 -1.000000e+00]
Esponenziale: [ 1.          4.81047738 23.14069263]
Logaritmo: [0.         2.30258509 4.60517019]


### 3.3 Esercizi di consolidamento

#### **Esercizio 7**
Crea un array con 5 valori casuali compresi tra 0 e 1 (usa `np.random.rand(5)`).
Applica la funzione np.sqrt per calcolare la radice quadrata di ogni elemento e visualizza il risultato.
<br><br>

#### **Esercizio 8**
Utilizza il broadcasting per sommare un vettore di 3 elementi a una matrice $2\times 3$ e poi applica `np.sin` all'array risultante.
<br><br>

#### **Esercizio 9**
Data una matrice $4\times 4$ di numeri casuali interi compresi tra 0 e 10, calcola:
* La somma di tutti gli elementi
* La media degli elementi
* Il massimo e il minimo

In [7]:
# Soluzioni
import numpy as np

# Esercizio 7
# Crea un array con 5 valori casuali compresi tra 0 e 1 (usa np.random.rand(5)).
# Applica la funzione np.sqrt per calcolare la radice quadrata di ogni elemento e visualizza il risultato.
print("Esercizio 7:")
array_casuale = np.random.rand(5)
print("Array casuale:", array_casuale)
radice_quadrata = np.sqrt(array_casuale)
print("Radice quadrata:", radice_quadrata)
print("Fine Esercizio 7\n")

# Esercizio 8
# Utilizza il broadcasting per sommare un vettore di 3 elementi a una matrice 2x3 e poi applica np.sin all'array risultante.
print("Esercizio 8:")
matrice = np.random.rand(2, 3)
vettore = np.random.rand(3)
print("Matrice:\n", matrice)
print("Vettore:\n", vettore)
risultato = np.sin(matrice + vettore)
print("Risultato:\n", risultato)
print("Fine Esercizio 8\n")

# Esercizio 9
# Data una matrice 4x4 di numeri casuali interi compresi tra 0 e 10, calcola:
# La somma di tutti gli elementi
# La media degli elementi
# Il massimo e il minimo
print("Esercizio 9:")
matrice_4x4 = np.random.randint(0, 11, size=(4, 4)) # Genero numeri casuali tra 0 e 10 inclusi
print("Matrice 4x4:\n", matrice_4x4)
somma = np.sum(matrice_4x4)
media = np.mean(matrice_4x4)
massimo = np.max(matrice_4x4)
minimo = np.min(matrice_4x4)
print("Somma:", somma)
print("Media:", media)
print("Massimo:", massimo)
print("Minimo:", minimo)
print("Fine Esercizio 9")

Esercizio 7:
Array casuale: [0.51737164 0.15413368 0.68446976 0.72037061 0.85658041]
Radice quadrata: [0.71928551 0.39259862 0.82732688 0.84874649 0.92551629]
Fine Esercizio 7

Esercizio 8:
Matrice:
 [[0.40799591 0.32949844 0.14570312]
 [0.90478958 0.14078957 0.01815283]]
Vettore:
 [0.44619106 0.75979601 0.78398848]
Risultato:
 [[0.75403714 0.88630039 0.80143553]
 [0.97593766 0.78369078 0.71884631]]
Fine Esercizio 8

Esercizio 9:
Matrice 4x4:
 [[ 2 10  5  0]
 [ 8 10  2  2]
 [ 5  1 10  4]
 [ 7  9  1  9]]
Somma: 85
Media: 5.3125
Massimo: 10
Minimo: 0
Fine Esercizio 9


## 4. Aggregazioni, reshaping, stacking e splitting

### 4.1 Operazioni di aggregazione

In [ ]:
mat = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Somma totale:", np.sum(mat))
print("Media totale:", np.mean(mat))
print("Valore massimo:", np.max(mat))
print("Valore minimo:", np.min(mat))
print("Deviazione standard:", np.std(mat))

### 4.2 Reshaping degli array

In [ ]:
arr = np.arange(12)  # crea un array con 12 elementi
mat_3x4 = arr.reshape((3, 4))  # trasforma in una matrice 3x4
print("Array originale:", arr)
print("Matrice 3x4:\n", mat_3x4)

# Appiattisci l'array
flat = mat_3x4.flatten()
print("Array appiattito:", flat)

### 4.3 Stacking

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

h_stack = np.hstack((a, b))
v_stack = np.vstack((a, b))

print("Horizontal stacking:", h_stack)
print("Vertical stacking:\n", v_stack)

### 4.4 Splitting

In [ ]:
arr = np.arange(10)
split_arr = np.split(arr, 2)  # divide in 2 parti
print("Array diviso in 2 parti:", split_arr)

### 4.5 Esercizi di consolidamento

#### **Esercizio 10**
Crea un array di 12 elementi usando `np.arange(12)`.
Trasforma questo array in una matrice $3\times 4$.
Calcola la somma lungo le colonne e lungo le righe.
<br><br>

#### **Esercizio 11**
Data una matrice $4\times $4, utilizza lo stacking per creare:
* Un array in cui le righe siano concatenate (orizzontalmente)
* Un array in cui le colonne siano concatenate (verticalmente)
<br><br>

#### **Esercizio 12**
Usa `np.split` per dividere un array 1D di 16 elementi in 4 sub-array uguali.
Verifica la dimensione di ciascun sub-array.

In [8]:
# Soluzioni
import numpy as np

# Esercizio 10
# Crea un array di 12 elementi usando `np.arange(12)`.
# Trasforma questo array in una matrice $3\times 4$.
# Calcola la somma lungo le colonne e lungo le righe.
print("Esercizio 10:")
array_12 = np.arange(12)
matrice_3x4 = array_12.reshape(3, 4)
print("Matrice 3x4:\n", matrice_3x4)
somma_colonne = np.sum(matrice_3x4, axis=0)  # Somma lungo le colonne (axis=0)
somma_righe = np.sum(matrice_3x4, axis=1)  # Somma lungo le righe (axis=1)
print("Somma lungo le colonne:", somma_colonne)
print("Somma lungo le righe:", somma_righe)
print("Fine Esercizio 10\n")


# Esercizio 11
# Data una matrice $4\times 4$, utilizza lo stacking per creare:
# * Un array in cui le righe siano concatenate (orizzontalmente)
# * Un array in cui le colonne siano concatenate (verticalmente)
print("Esercizio 11:")
matrice_4x4 = np.random.randint(0, 10, size=(4, 4))  # Matrice 4x4 con valori casuali
print("Matrice 4x4:\n", matrice_4x4)
orizzontale = np.hstack(matrice_4x4) # Concatenazione orizzontale delle righe
verticale = np.vstack(matrice_4x4) # Concatenazione verticale delle colonne

print("Stacking orizzontale:\n", orizzontale)
print("Stacking verticale:\n", verticale)
print("Fine Esercizio 11\n")

# Esercizio 12
# Usa `np.split` per dividere un array 1D di 16 elementi in 4 sub-array uguali.
# Verifica la dimensione di ciascun sub-array.
print("Esercizio 12:")
array_16 = np.arange(16)
sub_array = np.split(array_16, 4) # Divide l'array in 4 parti uguali
print("Sub-array:\n", sub_array)
for i, arr in enumerate(sub_array):
    print(f"Dimensioni del sub-array {i+1}:", arr.shape)
print("Fine Esercizio 12")

Esercizio 10:
Matrice 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Somma lungo le colonne: [12 15 18 21]
Somma lungo le righe: [ 6 22 38]
Fine Esercizio 10

Esercizio 11:
Matrice 4x4:
 [[2 5 2 8]
 [9 6 1 6]
 [1 6 5 1]
 [6 7 1 9]]
Stacking orizzontale:
 [2 5 2 8 9 6 1 6 1 6 5 1 6 7 1 9]
Stacking verticale:
 [[2 5 2 8]
 [9 6 1 6]
 [1 6 5 1]
 [6 7 1 9]]
Fine Esercizio 11

Esercizio 12:
Sub-array:
 [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11]), array([12, 13, 14, 15])]
Dimensioni del sub-array 1: (4,)
Dimensioni del sub-array 2: (4,)
Dimensioni del sub-array 3: (4,)
Dimensioni del sub-array 4: (4,)
Fine Esercizio 12


## 5. Operazioni di algebra lineare e statistica



### 5.1 Algebra lineare

* Prodotto scalare e matriciale

In [ ]:
# Prodotto scalare (dot product)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Prodotto scalare:", dot_product)

# Prodotto matriciale
mat1 = np.array([[1, 2],
                 [3, 4]])
mat2 = np.array([[2, 0],
                 [1, 2]])
prod_mat = np.matmul(mat1, mat2)
print("Prodotto matriciale:\n", prod_mat)

Prodotto scalare: 32
Prodotto matriciale:
 [[ 4  4]
 [10  8]]


* Inversione e determinante

In [ ]:
A = np.array([[4, 7],
              [2, 6]])
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print("Determinante di A:", det_A)
print("Inversa di A:\n", inv_A)

### 5.2 Funzioni statistiche

In [ ]:
data = np.array([3, 7, 5, 9, 1, 4])
print("Mediana:", np.median(data))
print("Percentile al 25%:", np.percentile(data, 25))
print("Varianza:", np.var(data))

### 5.3 Generazione di numeri casuali

In [ ]:
# Numeri casuali uniformi tra 0 e 1
uniform_rand = np.random.rand(5)
print("Uniform random:", uniform_rand)

# Numeri casuali da una distribuzione normale standard
normal_rand = np.random.randn(5)
print("Normal random:", normal_rand)

# Numeri interi casuali in un intervallo
int_rand = np.random.randint(0, 10, size=5)
print("Interi casuali:", int_rand)

# Imposta il seed per la riproducibilità
np.random.seed(42)

### 5.4 Esercizi di consolidamento

##### **Esercizio 13**
Crea due vettori di 4 elementi ciascuno con numeri casuali interi da 1 a 10.
Calcola il prodotto scalare tra di essi.
<br><br>

##### **Esercizio 14**
Crea una matrice $2\times 2$ con numeri interi a tua scelta.
Calcola il determinante e, se il determinante non è zero, calcola l'inversa della matrice.
<br><br>

##### **Esercizio 15**
Data una serie di 20 numeri casuali generati con `np.random.rand(20)`, calcola:
* La media
* La mediana
* La varianza
Confronta i risultati e commenta eventuali discrepanze.
<br><br>

##### **Esercizio 16**
* Simula il lancio di un dado 1000 volte (i valori devono essere interi da 1 a 6).
* Conta la frequenza di ciascun risultato e visualizza i conteggi.
<br><br>

##### **Esercizio 17**
* Genera 500 numeri casuali distribuiti uniformemente tra 0 e 100.
* Calcola la media e la deviazione standard e discuti se i valori rispecchiano quelli teorici di una distribuzione uniforme.

In [9]:
# Soluzioni
import numpy as np

# Esercizio 13
# Crea due vettori di 4 elementi ciascuno con numeri casuali interi da 1 a 10.
# Calcola il prodotto scalare tra di essi.
print("Esercizio 13:")
vettore1 = np.random.randint(1, 11, size=4)  # Genero 4 numeri casuali tra 1 e 10 (inclusi)
vettore2 = np.random.randint(1, 11, size=4)
print("Vettore 1:", vettore1)
print("Vettore 2:", vettore2)

prodotto_scalare = np.dot(vettore1, vettore2)
print("Prodotto scalare:", prodotto_scalare)
print("Fine Esercizio 13\n")


# Esercizio 14
# Crea una matrice 2x2 con numeri interi a tua scelta.
# Calcola il determinante e, se il determinante non è zero, calcola l'inversa della matrice.
print("Esercizio 14:")
matrice = np.array([[1, 2],
                   [3, 4]])
print("Matrice:\n", matrice)

determinante = np.linalg.det(matrice)
print("Determinante:", determinante)

if determinante != 0:
    inversa = np.linalg.inv(matrice)
    print("Inversa:\n", inversa)
else:
    print("La matrice non è invertibile (determinante = 0)")
print("Fine Esercizio 14\n")


# Esercizio 15
# Data una serie di 20 numeri casuali generati con `np.random.rand(20)`, calcola:
# * La media
# * La mediana
# * La varianza
# Confronta i risultati e commenta eventuali discrepanze.
print("Esercizio 15:")
numeri_casuali = np.random.rand(20)
print("Numeri casuali:", numeri_casuali)

media = np.mean(numeri_casuali)
mediana = np.median(numeri_casuali)
varianza = np.var(numeri_casuali)

print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)

# Commento: In una distribuzione uniforme tra 0 e 1, la media teorica è 0.5 e la varianza è 1/12.
# I valori ottenuti potrebbero discostarsi leggermente a causa della casualità del campione.
print("Fine Esercizio 15\n")


# Esercizio 16
# * Simula il lancio di un dado 1000 volte (i valori devono essere interi da 1 a 6).
# * Conta la frequenza di ciascun risultato e visualizza i conteggi.
print("Esercizio 16:")
lanci_dado = np.random.randint(1, 7, size=1000)  # Simula 1000 lanci di un dado (da 1 a 6)

conteggi = np.bincount(lanci_dado)[1:]  # Conta le frequenze (escludendo lo 0)
print("Frequenza dei risultati:", conteggi)

# Visualizza la distribuzione delle frequenze (opzionale)
# import matplotlib.pyplot as plt
# plt.hist(lanci_dado, bins=np.arange(1, 8)) # creo istogramma di frequenze
# plt.xlabel("Risultato del lancio")
# plt.ylabel("Frequenza")
# plt.title("Distribuzione dei lanci di un dado")
# plt.show()
print("Fine Esercizio 16\n")


# Esercizio 17
# * Genera 500 numeri casuali distribuiti uniformemente tra 0 e 100.
# * Calcola la media e la deviazione standard e discuti se i valori rispecchiano quelli teorici di una distribuzione uniforme.
print("Esercizio 17:")
numeri_uniformi = np.random.uniform(0, 100, size=500)
media_uniforme = np.mean(numeri_uniformi)
deviazione_standard_uniforme = np.std(numeri_uniformi)

print("Media:", media_uniforme)
print("Deviazione standard:", deviazione_standard_uniforme)

# Per una distribuzione uniforme tra a e b:
# Media teorica = (a + b) / 2 = (0 + 100) / 2 = 50
# Deviazione standard teorica = (b - a) / sqrt(12) = 100 / sqrt(12) ≈ 28.87

# I valori ottenuti dovrebbero essere vicini ai valori teorici, con possibili piccole variazioni a causa della casualità del campione.
print("Fine Esercizio 17")

Esercizio 13:
Vettore 1: [10 10  7  9]
Vettore 2: [10  1 10  8]
Prodotto scalare: 252
Fine Esercizio 13

Esercizio 14:
Matrice:
 [[1 2]
 [3 4]]
Determinante: -2.0000000000000004
Inversa:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Fine Esercizio 14

Esercizio 15:
Numeri casuali: [0.45838969 0.49445877 0.04206489 0.67404336 0.7852165  0.24616665
 0.52065778 0.30953687 0.55847778 0.46105673 0.83642947 0.89605725
 0.28296307 0.98800132 0.82276895 0.71439502 0.57300948 0.42416748
 0.85839529 0.67638625]
Media: 0.5811321290949408
Mediana: 0.5657436298178466
Varianza: 0.0586805018579883
Fine Esercizio 15

Esercizio 16:
Frequenza dei risultati: [177 172 154 162 155 180]
Fine Esercizio 16

Esercizio 17:
Media: 45.82174621240261
Deviazione standard: 28.357483375745122
Fine Esercizio 17


## 6. Esercizi di approfondimento

#### **Esercizio 18**
Crea un dataset fittizio:
* Genera una matrice $50\times 3$ dove ogni riga rappresenta un campione con 3 caratteristiche (usa np.random.rand o np.random.randint a tuo piacimento).
* Calcola la media e la deviazione standard per ogni colonna.
* Normalizza i dati (sottrai la media e dividi per la deviazione standard).
<br><br>

#### **Esercizio 19**
Costruisci una funzione che:
* Accetti in input una matrice di dati
* Calcoli e restituisca la matrice di covarianza
* Verifichi che la matrice di covarianza sia simmetrica
<br><br>

#### **Esercizio 20**
Simula un piccolo studio statistico:
* Genera dati casuali per rappresentare l'altezza e il peso di 200 persone (ad esempio, altezze normali e pesi con una correlazione ragionevole).
* Calcola le statistiche principali (media, mediana, varianza) per altezza e peso.
* Verifica la correlazione tra le due variabili (puoi usare anche `np.corrcoef`).
* Scrivi un breve commento sui risultati ottenuti.

In [10]:
# Soluzioni
import numpy as np

# Esercizio 18
# Crea un dataset fittizio:
# * Genera una matrice 50x3 dove ogni riga rappresenta un campione con 3 caratteristiche (usa np.random.rand o np.random.randint a tuo piacimento).
# * Calcola la media e la deviazione standard per ogni colonna.
# * Normalizza i dati (sottrai la media e dividi per la deviazione standard).
print("Esercizio 18:")
dataset = np.random.rand(50, 3)  # Matrice 50x3 con valori casuali tra 0 e 1
print("Dataset originale:\n", dataset)

media_colonne = np.mean(dataset, axis=0)
deviazione_standard_colonne = np.std(dataset, axis=0)

print("\nMedia delle colonne:", media_colonne)
print("Deviazione standard delle colonne:", deviazione_standard_colonne)

dataset_normalizzato = (dataset - media_colonne) / deviazione_standard_colonne
print("\nDataset normalizzato:\n", dataset_normalizzato)
print("Fine Esercizio 18\n")


# Esercizio 19
# Costruisci una funzione che:
# * Accetti in input una matrice di dati
# * Calcoli e restituisca la matrice di covarianza
# * Verifichi che la matrice di covarianza sia simmetrica
print("Esercizio 19:")
def calcola_matrice_covarianza(matrice_dati):
    # Calcolo la matrice di covarianza usando la funzione np.cov
    matrice_covarianza = np.cov(matrice_dati, rowvar=False)

    # Verifica di simmetria
    simmetrica = np.allclose(matrice_covarianza, matrice_covarianza.T)

    print("Matrice di Covarianza:\n", matrice_covarianza)
    print("La matrice è simmetrica:", simmetrica)
    return matrice_covarianza

# Esempio di utilizzo:
dati_esempio = np.random.rand(5, 3)  # matrice di esempio
calcola_matrice_covarianza(dati_esempio)

print("Fine Esercizio 19\n")


# Esercizio 20
# Simula un piccolo studio statistico:
# * Genera dati casuali per rappresentare l'altezza e il peso di 200 persone (ad esempio, altezze normali e pesi con una correlazione ragionevole).
# * Calcola le statistiche principali (media, mediana, varianza) per altezza e peso.
# * Verifica la correlazione tra le due variabili (puoi usare anche `np.corrcoef`).
# * Scrivi un breve commento sui risultati ottenuti.
print("Esercizio 20:")
np.random.seed(0) # fisso il seed per riproducibilità

# Simulo dati per altezza (distribuzione normale)
altezze = np.random.normal(170, 10, 200)

# Simulo dati per peso (con correlazione con l'altezza)
pesi = 0.7 * altezze + np.random.normal(0, 5, 200)


print("Altezza:\nMedia:", np.mean(altezze),
      "\nMediana:", np.median(altezze),
      "\nVarianza:", np.var(altezze))

print("\nPeso:\nMedia:", np.mean(pesi),
      "\nMediana:", np.median(pesi),
      "\nVarianza:", np.var(pesi))

# Calcolo la correlazione tra altezza e peso
correlazione = np.corrcoef(altezze, pesi)[0, 1]
print("\nCorrelazione tra altezza e peso:", correlazione)

print("\nCommento: La correlazione positiva tra altezza e peso è attesa. Le statistiche principali offrono un riepilogo dei dati simulati.")

print("Fine Esercizio 20")

Esercizio 18:
Dataset originale:
 [[1.11386248e-01 2.58296559e-01 6.87384047e-01]
 [1.14252301e-01 5.47759279e-01 5.29078310e-01]
 [2.58073209e-01 1.58718726e-01 2.65940478e-01]
 [2.92813675e-01 2.19074713e-01 6.94237223e-01]
 [8.16849924e-01 7.81143138e-01 8.69278841e-02]
 [9.13730602e-01 9.90157717e-01 7.51194458e-01]
 [5.06157668e-01 4.95138671e-01 8.52484688e-01]
 [5.06755330e-01 2.56733505e-01 3.10695553e-01]
 [3.49234464e-01 1.79978694e-01 3.93707403e-01]
 [6.00418317e-01 3.67589366e-01 7.25757814e-01]
 [8.11579451e-01 2.46823999e-01 2.87156427e-01]
 [6.87999503e-01 2.03643990e-02 5.51857471e-01]
 [1.18015318e-01 3.51195777e-01 8.66168317e-01]
 [1.69587339e-01 5.16896887e-01 2.18807648e-01]
 [8.99472449e-01 7.81150249e-01 8.22796505e-01]
 [8.49793231e-01 9.97130712e-01 6.77033414e-01]
 [2.88974656e-02 8.05320751e-01 4.07023671e-01]
 [3.89726380e-01 7.07087815e-02 2.43592396e-01]
 [5.12886865e-02 7.37963530e-01 4.41437948e-02]
 [6.74160760e-01 6.61656542e-01 2.61914217e-01]
 [8.37