In [18]:
import numpy as np

In [19]:
def costruisci_matrice(m, n, x):
    # Creare un array di numeri consecutivi di lunghezza m * n, a partire da x
    elementi = np.arange(x, x + m * n)
    # Ridimensionare l'array in una matrice m x n
    matrice = elementi.reshape(m, n)
    return matrice

# Esempio di utilizzo:
m = 3  # numero di righe
n = 4  # numero di colonne
x = 5  # valore iniziale
matrice = costruisci_matrice(m, n, x)
print(matrice)


[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
